# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  test:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: node:18.15.0-slim
    working_directory: ~/compass-portal
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - restore_cache:
          keys:
            - compass-portal-v1-deps-{{ checksum "package.json" }}
            - compass-portal-v1-deps-
      - run:
          command: |
            npm config set registry https://registry.npmmirror.com/
            npm install
            npm run lint
      - save_cache:
          paths:
            - node_modules
          key: compass-portal-v1-deps-{{ checksum "package.json" }}

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  lint-and-test:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
